type User @table {
  id: String! @default(expr: "auth.uid")
  email: String!
  displayName: String!
  createdAt: Timestamp!
}

type Player @table {
  user: User!
  name: String!
  born: Date!
  avatarId: Int!
}

type GameSession @table {
  chapter: String!
  level: Int!
  score: Int!
  durationSeconds: Int!
  playedAt: Timestamp!
  player: Player
}
